options:
    defClr: &5
    numClr: &a
    plrClr: &b
    itemClr: &b
    keyClr: &7
    multStr: " &8× "

on load:
    set {solstice_shard} to first element of loot of loot table "conflux_seasons:solstice_shard"

command /sols-give-item <integer> [<player>]:
    permission: server.admin
    trigger:
        if arg-2 is set:
            giveSols(arg-1,arg-2,true)
        else:
            giveSols(arg-1,player,true)
command /sols-give <integer> [<player>]:
    permission: server.admin
    trigger:
        if arg-2 is set:
            giveSols(arg-1,arg-2,false)
        else:
            giveSols(arg-1,player,false)

local function giveSols(amt: integer, p: player, asItem: boolean):
    if {_asItem} is true:
        give {_amt} of {solstice_shard} to {_p}
    else:
        add {_amt} to score of {_p} for objective with id "solstice_shards"

on custom click:
    if event-namespacedkey is "conflux_seasons:shop_open":
        make player execute command "function conflux_seasons:shop/pre_open"
    else:
        set {_payload} to event-nbt
        if event-namespacedkey is "conflux_seasons:shop_buy":
            set {_key} to string tag "index" of {_payload}
            set {_index} to {sols_shop.items.index::%{_key}%}
            add player to {sols_shop.players::*}
            add 1 to {sols_shop.players::%player%::%{_key}%}
            make player execute command "function conflux_seasons:shop/buy/check_balance with storage conflux_seasons:shop items[%{_index}%]"
        else if event-namespacedkey is "conflux_seasons:shop_withdraw_sols":
            set {_amt} to float tag "withdraw_range" of {_payload}
            if {_amt} > 0:
                giveSols({_amt}*-1,player,false)
                giveSols({_amt},player,true)
        else if event-namespacedkey is "conflux_seasons:sols_noise_easter_egg":
            play sound "minecraft:block.amethyst_block.step" with pitch 1.4 at player for player

command /shop [<string>]:
    trigger:
        if arg-1 is "sols_noise_easter_egg":
            play sound "minecraft:block.amethyst_block.step" with pitch 1.4 at player for player
        else:
            make player execute command "function conflux_seasons:shop/pre_open"


command /shop-init [<string>]:
    permission: server.admin
    trigger:
        if arg-1 is "confirm":
            make sender execute command "function conflux_seasons:shop/shop_defaults"
            make sender execute command "data modify storage conflux_seasons:shop items set value [{}]"
            make sender execute command "function conflux_seasons:shop/rebuild"
            
            delete {sols_shop.items.index::*}
            delete {sols_shop.items.cost::*}
            delete {sols_shop.items.name::*}
            loop {sols_shop.players::*}:
                delete {sols_shop.players::%loop-value%::*}
        else:
            send "Are you sure? Please send &7/shop-init confirm&r to confirm." to sender

command /shop-get-held-item:
    permission: server.admin
    trigger:
        send full nbt of player's held item to player

local function shopAdd(p: player, cost: integer, name: string, skKey: string):
    if {sols_shop.items.index::%{_skKey}%} is set:
        set {_size} to {sols_shop.items.index::%{_skKey}%}
        set {_updated} to true
    else:
        set {_size} to (size of {sols_shop.items.index::*}) + 1
        make {_p} execute command "data modify storage conflux_seasons:shop items append value {key:%{_skKey}%,icon:{atlas:""minecraft:items"",sprite:""conflux_seasons:item/solstice_shard""}}"
    make {_p} execute command "data modify storage conflux_seasons:shop items[%{_size}%] merge value {cost:%{_cost}%,label:{text:"" %{_name}% ""}}"
    make {_p} execute command "data modify storage conflux_seasons:shop items[%{_size}%].item set from entity @s SelectedItem"
    make {_p} execute command "function conflux_seasons:shop/rebuild"
    set {sols_shop.items.index::%{_skKey}%} to {_size}
    set {sols_shop.items.cost::%{_skKey}%} to {_cost}
    set {sols_shop.items.name::%{_skKey}%} to {_name}
    
    if {_updated} is set:
        send "&aUpdated %{_skKey}% with values name: %{_name}%, cost: %{_cost}% at index %{_size}%" to {_p}
    else:
        send "&aAdded %{_skKey}% with values name: %{_name}%, cost: %{_cost}% at index %{_size}%" to {_p}
        
#                        SkKey    Cost      Name
command /shop-set-keyed <string> <integer> <text>:
    permission: server.admin
    trigger:
        shopAdd(player,arg-2,arg-3,arg-1)

on tab complete of "/shop-set-keyed":
	set tab completions for position 1 to "new_key", and indexes of {sols_shop.items.index::*}
	set tab completions for position 2 to "cost"
	set tab completions for position 3 to "name"

#                       SkKey    Atlas  Sprite
command /shop-set-icon <string> <text> <text>:
    permission: server.admin
    trigger:
        if arg-1 is set:
            if arg-2 is not set:
                set {_atlas} to "minecraft:items"
            else:
                set {_atlas} to arg-2
            if arg-3 is not set:
                set {_sprite} to "conflux_seasons:item/solstice_shard"
            else:
                set {_sprite} to arg-3
            set {_index} to {sols_shop.items.index::%arg-1%}
            make player execute command "data modify storage conflux_seasons:shop items[%{_index}%].icon set value {atlas:""%{_atlas}%"",sprite:""%{_sprite}%"",shadow_color:0}"
            make player execute command "function conflux_seasons:shop/rebuild"
        else:
            send "Must specify the key!" to player

on tab complete of "/shop-set-icon":
    set tab completions for position 1 to indexes of {sols_shop.items.index::*}
    set tab completions for position 2 to "atlas"
    set tab completions for position 3 to "sprite"

command /shop-remove <string>:
    permission: server.admin
    trigger:
        set {_key} to arg-1
        set {_index} to {sols_shop.items.index::%{_key}%}
        make player execute command "data remove storage conflux_seasons:shop items[%{_index}%]"
        delete {sols_shop.items.index::%{_key}%}
        delete {sols_shop.items.name::%{_key}%}
        delete {sols_shop.items.cost::%{_key}%}
        loop {sols_shop.items.index::*}:
            if loop-value > {_index}:
                set {sols_shop.items.index::%loop-index%} to loop-value - 1 # Since the storage data will decrements its indexes, update tracking in skript too

on tab complete of "/shop-remove":
    set tab completions for position 1 to indexes of {sols_shop.items.index::*}


#                           old      new
#command /shop-transfer-key <string> <string>:
##    permission: server.admin
#    trigger:
#        if indexes of {sols_shop.items.index::*} contains 
#        set {sols_shop.items.index::%arg-1%} to {sols_shop.items.index::%arg-1%}
#        set {_index} to {sols_shop.items.index::%arg-1%}

command /shop-minimsg <string>:
    trigger:
        send arg-1 to sender

local function solsSprite(amt: integer, s: sender, format: string = "00"):: string:
    if {_s} is console:
        return "&d%formatNumber({_amt},{_format})% Sols"
    else:
        return "&d%formatNumber({_amt},{_format})%&r<click:run_command:shop sols_noise_easter_egg><sprite:""minecraft:items"":""conflux_seasons:item/solstice_shard""></click>"

local function itemString(key: string, s: sender):: string:
    return "%solsSprite({sols_shop.items.cost::%{_key}%},{_s})% {@itemClr}%{sols_shop.items.name::%{_key}%}% {@keyClr}(%{_key}%)"

command /shop-records-player [<string>] [<string>]:
    trigger:
        if sender is not op:
            set {_p} to player
        else:
            if all:
                arg-1 is set
                arg-1 is not "*"
            then:
                set {_p} to arg-1 parsed as player
        set {_solsTotal} to 0
        set {_total} to 0
        if {_p} is set:
            set {_report} to "{@defClr}Purchase History for {@plrClr}%{_p}%"
            loop {sols_shop.players::%{_p}%::*}:
                if any:
                    arg-2 is not set
                    arg-2 is loop-index
                then:
                    set {_itemCost} to {sols_shop.items.cost::%loop-index%}
                    add ({_itemCost} * loop-value) to {_solsTotal}
                    add loop-value to {_total}
                    add "%nl%{@numClr}%formatNumber(loop-value,"00")%%{@multStr}%%itemString(loop-index,sender)%" to {_report}
            if {_total} is 1:
                set {_purchaseStr} to "purchase"
            else:
                set {_purchaseStr} to "purchases"
            add "%nl%{@defClr}Total of %solsSprite({_solsTotal},sender)%{@defClr} spent across {@numClr}%{_total}%{@defClr} %{_purchaseStr}%." to {_report}
        else:
            set {_totalPlrs} to 0
            set {_report} to "{@defClr}Purchase History"
            loop {sols_shop.players::*}:
                set {_p} to loop-value
                add 1 to {_totalPlrs}
                if {sols_shop.players::%{_p}%::*} is set:
                    loop {sols_shop.players::%{_p}%::*}:
                        send "%loop-index-2% = %arg-2%" to sender
                        if any:
                            arg-2 is not set
                            arg-2 is loop-index-2
                        then:
                            set {_itemName} to {sols_shop.items.name::%loop-index-2%}
                            set {_itemCost} to {sols_shop.items.cost::%loop-index-2%}
                            add ({_itemCost} * loop-value-2) to {_solsTotal}
                            add loop-value-2 to {_total}
                            add "%nl%{@plrClr}%{_p}% {@numClr}%formatNumber(loop-value-2,"00")%%{@multStr}%%itemString(loop-index-2,sender)%" to {_report}
            if {_total} is 1:
                set {_purchaseStr} to "purchase"
            else:
                set {_purchaseStr} to "purchases"
            if {_totalPlrs} is 1:
                set {_plrStr} to "player"
            else:
                set {_plrStr} to "players"
            add "%nl%{@defClr}Total of %solsSprite({_solsTotal},sender)%{@defClr} spent across {@numClr}%{_total}%{@defClr} %{_purchaseStr}% and {@numClr}%{_totalPlrs}%{@defClr} %{_plrStr}%." to {_report}
        if sender is console:
            set {_report} to "&rGenerating Sols Shop report...%nl%%{_report}%"
        send {_report} to sender

on tab complete of "/shop-records-player":
    set tab completions for position 1 to {sols_shop.players::*}
    set tab completions for position 2 to indexes of {sols_shop.items.index::*}
        
command /shop-records-item [<string>]:
    permission: server.admin
    trigger:
        set {_total} to 0
        if arg-1 is set:
            set {_key} to arg-1
            set {_report} to "{@defClr}Purchase Records for %itemString({_key},sender)%"
            loop {sols_shop.players::*}:
                set {_plr} to loop-value
                if {sols_shop.players::%{_plr}%::%{_key}%} is set:
                    set {_plrPurchased} to {sols_shop.players::%{_plr}%::%{_key}%}
                    add {_plrPurchased} to {_total}
                    add "%nl%{@numClr}%formatNumber({_plrPurchased} ,"00")%%{@multStr}%{@plrClr}%{_plr}%" to {_report}
            add "%nl%{@defClr}Total Purchased:{@numClr} %{_total}%" to {_report}
        else:
            set {_report} to "{@defClr}Item Purchase Records"
            loop indexes of {sols_shop.items.index::*}:
                set {_key} to loop-value
                loop {sols_shop.players::*}:
                    set {_plr} to loop-value-2
                    if {sols_shop.players::%{_plr}%::%{_key}%} is set:
                        set {_plrPurchased} to {sols_shop.players::%{_plr}%::%{_key}%}
                        add {_plrPurchased} to {_total}
                add "%nl%{@numClr}%formatNumber({_total} ,"000")%%{@multStr}%%itemString({_key},sender)%" to {_report}
                
        if sender is console:
            set {_report} to "&rGenerating Sols Shop report...%nl%%{_report}%"
        send {_report} to sender

on tab complete of "/shop-records-item":
    set tab completions for position 1 to indexes of {sols_shop.items.index::*}